documentation: Documentation/*.md
abstract: Documentation/Sections/*.md
custom_categories:
  - name: Guides
    children:
      - TestLauncher
      - System arguments
      - Custom arguments
      - Launch environments
  - name: Launch arguments
    children:
      - SystemLanguages
      - SystemLocale
      - SoftwareKeyboards
      - HardwareKeyboards
      - SystemKeyboards
      - CoreDataOption
      - LocalizedStrings

      - LaunchArgument
      - LaunchArgumentWithSingleValue
      - LaunchArgumentWithMultipleValues
      - LaunchArgumentValue
  - name: Launch environments
    children:
      - EventLaunchEnvironment
      - ReminderLaunchEnvironment
      - ContactLaunchEnvironment
      - AnimationLaunchEnvironment
      - AutoMateLaunchEnvironment

      - LaunchEnvironment
      - LaunchEnvironments

      - LaunchEnvironmentProtocol
      - LaunchEnvironmentWithSingleValue
      - LaunchEnvironmentWithMultipleValues
      - CleanableLaunchEnvironment
      - CleanableLaunchEnvironmentWithMultipleValues
      - LaunchEnvironmentValue
      - LaunchEnvironmentResourceValue
  - name: XCTest
    children:
      - AppUITestCase
      - XCTestCase
      - XCUIApplication
      - XCUIElement
      - XCUIElementQuery
      - XCUIElementTypeQueryProvider
  - name: Page objects
    children:
      - BaseAppPageProtocol
      - BaseAppPage
      - ModalPage
      - PushedPage
      - HealthPermissionPage
  - name: Locators
    children:
      - Locator
      - KeyboardLocator
  - name: System alerts
    children:
      - SystemAlert
      - HealthAuthorizationDontAllowAlert
      - LocationAlwaysAlert
      - LocationUpgradeWhenInUseAlwaysAlert
      - LocationWhenInUseAlert
      - AddressBookAlert
      - BluetoothPeripheralAlert
      - CalendarAlert
      - CallsAlert
      - CameraAlert
      - MediaLibraryAlert
      - MicrophoneAlert
      - MotionAlert
      - PhotosAlert
      - RemindersAlert
      - SiriAlert
      - SpeechRecognitionAlert
      - WillowAlert
