language: objective-c
osx_image: xcode8.2

env:
  - NSUnbufferedIO=YES

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail && xcodebuild -workspace AutoMate.xcworkspace -scheme AutoMate -destination "platform=iOS Simulator,id=DB794781-65A7-4884-8D00-AAC3CBD39A44" test | xcpretty -c
  - pod --version && pod spec lint
