language: objective-c
osx_image: xcode8.3

env:
  global:
    - NSUnbufferedIO=YES
  matrix:
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPhone SE"      DESTINATION_OS="10.3.1"
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPhone 7"       DESTINATION_OS="10.3.1"
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPhone 7 Plus"  DESTINATION_OS="10.3.1"
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPad Air 2"                             DESTINATION_OS="10.3.1"
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPad Pro (10.5-inch)"                   DESTINATION_OS="10.3.1"
    - SCHEME="AutoMate iOS" PLATFORM="iOS Simulator"  DESTINATION_NAME="iPad Pro (12.9-inch) (2nd generation)"  DESTINATION_OS="10.3.1"

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

before_script:
  - swiftlint version
  - bundle exec pod --version
  - bundle exec fastlane --version
  - bundle exec fastlane snapshot reset_simulators --force --ios 10.3
  - bundle exec fastlane prepare

script:
  - bundle exec fastlane test "scheme:${SCHEME}" "destination:platform=${PLATFORM},name=${DESTINATION_NAME},OS=${DESTINATION_OS}"
  - bundle exec danger
  - bundle exec pod lib lint
